- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Clearing old HTML content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent
  ignore_errors: yes

- name: Create APP directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory
    mode: '0755'
  ignore_errors: yes

- name: Download and extracting the Component
  ansible.builtin.unarchive:
    src: http://172.31.2.21:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /usr/share/nginx/html/
    remote_src: yes

# Uncomment this only if you use GitHub to download the code directly
# - name: Copying the Frontend Contant to Nginx path
#   ansible.builtin.copy:
#     src: /tmp/frontend-main/static/
#     dest: /usr/share/nginx/html/
#     remote_src: yes           # Since the remote is on a remote machine, ensure you mention remote_src as yes

- name: Copying Nginx Config
  ansible.builtin.template:       # Copies the files from the files directory
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx       # Only when there is a chanve in the copy file, then only this handeler will be called

- name: Starting Frontend service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

#  When frontend service has to be restarted ?
#  Whenever there is a change in the roboshop.conf, only then I need a restart